CREATE DATABASE API_SPOTIFY;
USE API_SPOTIFY;


CREATE TABLE TB_MUSICAS(
	ID_MUSICA 			INT PRIMARY KEY AUTO_INCREMENT,
    NM_MUSICA 			VARCHAR(100),
    NM_ARTISTA			VARCHAR(100),
    VL_DURACAO			TIME,
    DT_LANCAMENTO		DATE,
    NM_ALBUM			VARCHAR(100),
    CAPA_ALBUM			VARCHAR(1000)
);

drop table tb_musicas;

INSERT INTO TB_MUSICAS(NM_MUSICA, NM_ARTISTA, VL_DURACAO, DT_LANCAMENTO, NM_ALBUM, CAPA_ALBUM)
		VALUES ('curls (instrumental)', 'Madvillain', '00:02:00', '2004/03/02', 'Madivillany', 'https://cdn.shopify.com/s/files/1/0043/7105/4710/products/Madvillain-Madvillainy-Instrumentals-STH2099_400x.jpg' );


	SELECT *
		FROM TB_MUSICAS;
