CREATE DATABASE DB_TASKS;
USE DB_TASKS;

CREATE TABLE TB_TASKS(
	ID_TASK				INT primary KEY auto_increment,
    DS_TASK				VARCHAR(100),
    NR_ORDER			INT,
    BT_FINISHED			BOOL,
    DT_CADASTRO			DATETIME
);



DROP table TB_TASKS;